AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates a natgateway in one of the public subnet. 
             Also add a Route for private subnets to redirect all internet traffic outwords (0.0.0.0/0) to be directed to NAT gateway.
Parameters: 
  EnvironmentName: 
    Type: String
    Default: Demo1
    Description: Name of the environment.

Resources:    
  NatGatewayOneAttachment:
    Type: AWS::EC2::EIP
    Properties:
        Domain: vpc
  NatGatewayOne:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayOneAttachment.AllocationId
      SubnetId: 
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'PublicSubnetOne']]      
  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: 
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'PrivateRouteTable']]         
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayOne          